name: Run Web App Test cases

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out Code
        uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.9

      - name: Installing dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Running Tests
        run: |
          python -m unittest test.py