
name: Run packer build on AWS

on:
  workflow_dispatch:
  push:
    branches:
     - 'main'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Github code checkout
        uses: actions/checkout@v1
      - name: Create a zip folder
        run: zip -r webapp.zip ./ -x *.git*
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name : Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ami.pkr.hcl
          working_directory: 'packer'

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.pkr.hcl
          working_directory: 'packer'

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: '-color=false -on-error=abort -var-file=dev.auto.pkrvars.hcl'
          target: ami.pkr.hcl
          working_directory: 'packer'
        env:
          PACKER_LOG: 1